on: workflow_dispatch

jobs:
  push-to-myget:
    runs-on: windows-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
        
      - name: setup nuget.exe
        uses: NuGet/setup-nuget@v1.0.5
      
      - name: build and push
        shell: pwsh
        run: |
          cd build
          .\build.ps1
          nuget pack build-for-myget.nuspec -version 3.3.0-beta.${env:GITHUB_RUN_NUMBER}
          $nupkgName = @(gci *.nupkg)[0].Name
          $mygetSourcePath = "https://www.myget.org/F/handycontrol"
          nuget setApiKey ${{ secrets.MYGETTOKEN }} -Source $mygetSourcePath
          nuget push $nupkgName -Source $mygetSourcePath
